<<<<<<< HEAD
apiVersion: extensions/v1beta1
=======
apiVersion: networking.k8s.io/v1
>>>>>>> b4d49223c5dc529c5dbbc63972077fac1843bdd2
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: myapp.com
    http:
      paths:
<<<<<<< HEAD
      - path: "/cart"       
        backend:
          serviceName: svc1
          servicePort: 80     
      - path: "/products"
        backend:
          serviceName: svc2
          servicePort: 80
=======
      - pathType: Prefix
        path: "/cart"
        backend:
          service:
            name: svc1
            port:
              number: 80
      - pathType: Prefix
        path: "/products"
        backend:
          service:
            name: svc2
            port:
              number: 80
>>>>>>> b4d49223c5dc529c5dbbc63972077fac1843bdd2
